# -- Site Configuration --
# Detailed language settings → languages.toml
# Theme parameters           → params.toml

theme   = "congo"
baseURL = "https://madoka-0w0.github.io/hugo-lab/"
title   = "まど研究室"

defaultContentLanguage         = "ja"
defaultContentLanguageInSubdir = false

enableRobotsTXT = true
summaryLength   = 0

[pagination]
  pagerSize = 15

[outputs]
  home = ["HTML", "RSS", "JSON"]

[privacy]
  [privacy.vimeo]
    enableDNT = true
  [privacy.x]
    enableDNT = true
  [privacy.youTube]
    privacyEnhanced = true

[services]
  [services.x]
    disableInlineCSS = true
