# -- English Navigation Menu --

[[main]]
  name   = "Research"
  url    = "/en/research/"
  weight = 10

[[main]]
  name   = "Members"
  url    = "/en/members/"
  weight = 20

[[main]]
  name   = "Publications"
  url    = "/publications/"
  weight = 30

[[main]]
  name   = "News"
  url    = "/en/news/"
  weight = 40

[[main]]
  name   = "Access"
  url    = "/en/access/"
  weight = 60
